server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix:classpath: /templates/
    suffix: .html
    cache: false
  datasource:
      url: jdbc:mysql://localhost:3306/blog?autoReconnect=true&charaEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
      tomcat:
        initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  hikari:
    # 连接池名
      pool-name: DateHikariCP
    # 最小空闲连接数
      minimum-idle: 5
    # 空闲连接存活最大时间，默认600000（10 分钟）i
      dle-timeout: 180000
    #最大连接数，默认10
      maximum-pool-size: 10
    #从连接池返回的连接的自动提交
      auto-commit: true
    #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
    #连接超时时间，默认30000（ 30秒）
      connection-timeout: 30000
    #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    #超时时间
    timeout: 10000ms
    #服务器地址
    host: localhost
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
#    password: 123456
    lettuce:
      pool:
        #最大连接数  默认8
        max-active: 1024
        #最大连接阻塞等待时间， 默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
mybatis:
    mapper-locations: classpath:mapper/*.xml

file:
  staticAccessPath: /uploadBlogImg/**
  uploadFolder: D:\\blog\\tylblog\\uploadBlogImg\\